# Generated by Django 3.0.8 on 2020-07-31 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LoanQualification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(help_text='optional', max_length=30)),
                ('lastname', models.CharField(help_text='optional', max_length=30)),
                ('email', models.EmailField(help_text='required', max_length=100)),
                ('id_number', models.IntegerField(help_text='required', max_length=50)),
                ('next_of_kin', models.CharField(help_text='optional', max_length=100)),
                ('kra_pin', models.CharField(help_text='required', max_length=100)),
                ('job_done', models.CharField(help_text='optional', max_length=255)),
                ('guarantor', models.CharField(help_text='optional', max_length=255)),
                ('given_item', models.CharField(help_text='optional', max_length=255)),
                ('price_of_item', models.CharField(help_text='optional', max_length=255)),
            ],
        ),
    ]
