# Generated by Django 3.0.8 on 2020-07-31 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loanqualification', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanqualification',
            name='id_number',
            field=models.IntegerField(help_text='required'),
        ),
    ]
